# Generated by Django 3.0.3 on 2020-03-09 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_publick',
            new_name='is_public',
        ),
    ]
