# Generated by Django 3.0.3 on 2020-03-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='relation_posts',
            field=models.ManyToManyField(blank=True, related_name='_post_relation_posts_+', to='blog.Post', verbose_name='関連記事'),
        ),
    ]
